name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Write runtime env.js from GitHub Secrets
        run: |
          mkdir -p src/assets
          cat > src/assets/env.js << EOF
          (function (window) {
            window.__env = window.__env || {};
            window.__env.apiUrl = '${{ secrets.API_URL }}';
          })(this);
          EOF

      - name: Build Angular app for GitHub Pages
        run: npm run build:ghpages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/rugby-score-card-app/browser
          cname: # Add your custom domain here if you have one
