name: Build and Deploy Backend API

on:
  push:
    branches: [main, master]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-backend

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  optionally-trigger-render-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Trigger Render deploy (optional)
        run: |
          if [ -n "${RENDER_DEPLOY_HOOK_URL}" ]; then
            echo "Triggering Render deploy..."
            curl -X POST -fsSL "$RENDER_DEPLOY_HOOK_URL"
          else
            echo "No Render hook set; skipping."
          fi
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

  optionally-trigger-railway-deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Trigger Railway deploy (optional)
        run: |
          if [ -n "${RAILWAY_DEPLOY_HOOK_URL}" ]; then
            echo "Triggering Railway deploy..."
            curl -X POST -fsSL "$RAILWAY_DEPLOY_HOOK_URL"
          else
            echo "No Railway hook set; skipping."
          fi
        env:
          RAILWAY_DEPLOY_HOOK_URL: ${{ secrets.RAILWAY_DEPLOY_HOOK_URL }}
